sonar.projectKey=validacion-redpulse
sonar.projectName=VALIDACION-REDPULSE
sonar.projectVersion=1.0

sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.login=sqp_fdeabcee018f18fee998260dbda61439d6d85bee

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml