sonar.projectKey=redpulse-validacion
sonar.projectName=Redpulse
sonar.projectVersion=1.0

#sonar.sources=src
#sonar.tests=src/tests
sonar.exclusions=src/secret_config.py

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8