sonar.projectKey=Redpulse
sonar.projectName=Redpulse
sonar.projectVersion=1.0

sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.login=sqp_cf29be354658f9f19e6d9cd74d71250bed485896

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml

